# HTTP 代理端口
port: 7890
# SOCKS5 代理端口
socks-port: 7891
# Linux 和 macOS 的 redir 代理端口
redir-port: 7892
# 允许局域网的连接
allow-lan: true
# 规则模式：Rule（规则） / Global（全局代理）/ Direct（全局直连）
mode: Rule
# 设置日志输出级别 (默认级别：silent，即不输出任何内容，以避免因日志内容过大而导致程序内存溢出）。
# 5 个级别：silent / info / warning / error / debug。级别越高日志输出量越大，越倾向于调试，若需要请自行开启。
log-level: info
# Clash 的 RESTful API
external-controller: '127.0.0.1:9090'
secret: ''
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:53
  enhanced-mode: redir-host
  nameserver:
  - 119.29.29.29
  - 114.114.114.114
  - 223.5.5.5
  - 1.2.4.8
  fallback:
  - tls://dns.rubyfish.cn:853
  - tls://1.0.0.1:853
  - tls://dns.google:853
cfw-bypass:
  # 直连列表
  - <local>
cfw-latency-timeout: 3000
# 打断连接
cfw-conn-break-strategy:
  proxy: none              # none/chain/all
  profile: true            # true/false
  mode: false              # true/false
Proxy:
  - name: Shadowsocks
    type: socks5
    server: 127.0.0.1
    port: 1080
Proxy Group:
  - name: Proxy
    type: select
    proxies:
      - Shadowsocks
Rule:
  - 'MATCH,DIRECT'
# 您可以将静态网页资源（如 clash-dashboard）放置在一个目录中，clash 将会服务于 `RESTful API/ui`
# 参数应填写配置目录的相对路径或绝对路径。
# external-ui: folder
#dns:
#  enable: true
#  ipv6: false
#  listen: 0.0.0.0:53
#  enhanced-mode: redir-host
#  nameserver:
#     - 117.50.10.10
#     - 114.114.114.114
#     - 119.29.29.29
#     - 180.76.76.76
#     - 1.2.4.8
#     - 223.5.5.5
#     - 8.8.8.8
#  fallback:
#     - tls://dns.rubyfish.cn:853
#     - tls://1.0.0.1:853
#     - tls://dns.google:853
# Clash for Windows
