# This is a basic workflow to help you get started with Actions

name: Update china_ip_list

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  schedule:
    - cron:  '0 0 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Get ip_list
      run: wget https://raw.githubusercontent.com/17mon/china_ip_list/master/china_ip_list.txt

    # Runs a set of commands using the runners shell
    - name: Edit List
      run: sed 's/^/IP-CIDR,&/g' ./china_ip_list.txt > ./china_ip.list
        
    - name: commit
      uses: EndBug/add-and-commit@v4
      with:
        author_name: Judi
        author_email: wen10603654852@sina.com
        message: "Auto Update"
        add: "./china_ip.list"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
        
